package nl.suriani.tenniskata.domain.enumeration;

public enum MatchEventType {
	MATCH_CONFIRMED,
	MATCH_STARTED,
	POINT_PLAYER1,
	POINT_PLAYER2,
	DEUCE,
	ADVANTAGE_IN_PLAYER1,
	ADVANTAGE_IN_PLAYER2,
	GAME_PLAYER1,
	GAME_PLAYER2,
	TIE_BREAK,
	SET_PLAYER1,
	SET_PLAYER2,
	PLAYER1_WON,
	PLAYER2_WON,
	MATCH_CANCELLED
}
