package nl.suriani.tenniskata.domain.enumeration;

public enum MatchEventType {
	MATCH_CONFIRMED,
	MATCH_STARTED,
	POINT_TEAM1,
	POINT_TEAM2,
	DEUCE,
	ADVANTAGE_IN_TEAM1,
	ADVANTAGE_IN_TEAM2,
	GAME_TEAM1,
	GAME_TEAM2,
	TIE_BREAK,
	SET_TEAM1,
	SET_TEAM2,
	TEAM1_WON,
	TEAM2_WON,
	MATCH_CANCELLED
}
